### ISSUE TITLE
No digest mail when using cron

### ISSUE THREAD

**Issue by marcosegato** [ColdTrick/digest#26]
I'm testing this plugin with Elgg 1.9.x: if I try to generate the daily digest by linux cron (both with wget and lwp-request), it doesn't send any email.
Otherwise, if I visit the URL http://mysite/cron/daily by my browser, it creates all the expected emails.

Elgg 1.9.7 installation is up to date, I already tried with Digest v 3.0 and 2.1.1; with 2.2.1 I get a "500 Internal Server Error".

Thanks

**Comment by jdalsem** [comment]
If manually executing the cron url works, i expect nothing to be wrong with this plugin. However there could be a difference between logged in or logged out. Are you able to access the cron url when logged out? And does it send the mails? If that all works correctly there must be something else wrong (unrelated to the site i think). Is wget downloading anything?

**Comment by marcosegato** [comment]
I found a new detail that I hope can be useful: when someone creates a new wire post or he joins a group, the digest is generated by cron (wget) and it contains only these kind of posts.
But everytime the digest should process only blog posts, it doesn't send any email.
Is it possible that for some reason the upgrade lost some trigger on blog post objects?

No difference between logged in or logged out.

So, actually:
* if I use "/usr/bin/wget --output-document=/dev/null https://mysite/cron/daily/", the mail is not sent for blog posts (wget downloads an HTML page with the sentence "X notifications removed")
* if by my browser I visit the URL "https://mysite/cron/daily/", the mail is sent with with all the expecting content, both wire and group's joins and blog posts

Thanks for your help

**Comment by marcosegato** [comment]
> Are you able to access the cron url when logged out? And does it send the mails?

When logged out, it doesn't send any mail.

**Comment by oseg** [comment]
Hi Jeroen,

I have got the same issue as marcosegato.

After a few investigations I found out the root cause in lib/functions.php file at line 165 in digest_group function:

	// store current user
	$current_user = elgg_get_logged_in_user_entity();

if executed from a cron job (no user logged in) $current_user = null and then $userdata is empty.

I implemented a quick workaround (hope there is no side effect with login and logout):

	// store current user
	$current_user = elgg_get_logged_in_user_entity();
	if ($current_user == null)
        {
            $is_impersonate_session = login($user);
        }
    ...
	// save memory
	unset($userdata);
	
	// restore current user
        if($is_impersonate_session)
        {
            logout();
            unset($is_impersonate_session);
        }

**Comment by Facyla** [comment]
I encountered the same issue since June, on Elgg 1.12, except for the new members.

I haven't been able to track back what change broke the behaviour, but i suspect something with core handling of sessions, as it broke after i updated the core to latest 1.12.x version at that time.

Also, it doesn't affect the new members view, and this is te only one i use that does not use the user session to generate the view content.

However, oseg's patch is working, and as there is no planned new version for digest at this time, i thought it was a good idea to push the patch to the master branch, so here it is.

**Comment by Facyla** [comment]
Done for a separate patch for #30.
I'm updating the other patch so it actually performs login/logout, but without triggering any event.

**Comment by jeabakker** [comment]
I replace the session handling in 8930a65f073ecfd0c86c672801304bd002a18045 should no longer be an issue
